project:
  type: book

book:
  title: "ACE Methodology"
  author: "Jean-Claude HUSTACHE"
  date: "2022-04-22"
  chapters:
    - index.qmd
    - process-and-use.qmd
    - methodology.qmd
    - delays-and-cost.qmd
    - influencing-factors.qmd
    - bechmarking-and-ses.qmd
    - monetary-factors.qmd
    - references.qmd
  site-url: "https://eurocontrol.int/"
  link-external-newwindow: true
  navbar:
    background: light
    search: false
    title: false
    logo: "images/EUROCONTROL-logo-standard-rgb.svg"
    left:
      - text: "Aviation Intelligence"
        icon: "star"
        menu:
          - text: "**Home**"
            icon: "house-fill"
            href: "https://ansperformance.eu"
          - text: "**Balanced Scorecard**"
            icon: "grid-3x3-gap-fill"
            href: "https://www.eurocontrol.int/Economics/BalancedScorecard.html"
          - text: "<i class='fas fa-biohazard'></i> **COVID-19 crisis**"
            href: "https://ansperformance.eu/covid/"
          - text: "State and Airline response to Covid-19"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/covid19#response-to-covid-19"
          - text: "Grounded Aircraft"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/covid/acft_ground/"
          - text: "<i class='fas fa-plane-departure'></i> **Traffic**"
            href: "https://ansperformance.eu/traffic/"
          - text: "<i class='far fa-star fa-spin fa-fw'></i> Daily Traffic Variation & Restart <i class='far fa-star fa-spin fa-fw'></i>"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html"

      - text: "About"
        menu:
          - text: "About the PRC"
            href: "https://ansperformance.eu/about/prc/"
          - text: "About the PRU"
            href: "https://ansperformance.eu/about/us/"

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    include-in-header:
      - media/fontawesome.html
  pdf:
    documentclass: scrreprt
