project:
  type: book
  # post-render: pdfjam --no-tidy media/cover.pdf '1,2' _book/ACE-Handbook.pdf '-' media/cover.pdf '3,4' --outfile ACE-Handbook.pdf

bibliography: references.bib
link-citations: true
colorlinks: true
# csl: ieee-with-url.csl

format-links: [pdf]


format:
  html:
    theme:
      - cosmo
      - custom.scss
    code-link: true
    cover-image: cover.png
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: '^(?:http:|https:)\/\/ansperformance\.eu\/|^(?:http:|https:)\/\/.*ace-handbook\.netlify\.app\/'
    include-in-header:
      - media/fontawesome.html
      # UNCOMMENT for activating GA
      - media/analytics.html
  pdf:
    papersize: a4paper
    pdf-engine: xelatex
    documentclass: scrbook
    classoption: "openany,headsepline=on,footsepline=off,DIV=12,table"
    mainfont: Roboto
    # monofont: 'roboto-mono'
    keep-tex: true
    hyperrefoptions:
      - linktoc=all
    toccolor:  'blue'
    linkcolor: 'blue'
    urlcolor:  'blue'
    citecolor: 'blue'
    fontsize: 11pt
    # fig-pos: 'H'
    include-in-header:
      - text: |
         % make figure title, number and caption bold
         \usepackage[labelfont=bf,font=bf]{caption}
         %\usepackage[bottom=105pt]{geometry}
         % alternate row color in tables (https://github.com/jgm/pandoc/issues/7421#issuecomment-881732047)
         \usepackage{colortbl}
         \usepackage{etoolbox}
         \AtBeginEnvironment{longtable}{\rowcolors{2}{gray!25}{}}
         \apptocmd{\toprule}{\hiderowcolors}{}{}
         \apptocmd{\endhead}{\showrowcolors}{}{}
         \apptocmd{\endfirsthead}{\showrowcolors}{}{}
         % title font (https://stackoverflow.com/a/73689149)
         \newfontfamily\tfont{Roboto}
         \addtokomafont{title}{\tfont}
         \addtokomafont{chapter}{\tfont}
         \addtokomafont{section}{\tfont}


book:
  title: "ACE Handbook"
  author: "Performance Review Unit"
  date: "2023-03-01"
  date-format: long
  chapters:
    - index.qmd
    - process-and-use.qmd
    - methodology.qmd
    - delays-and-cost.qmd
    - influencing-factors.qmd
    - bechmarking-and-ses.qmd
    - monetary-factors.qmd
    - detail-ace-indicators.qmd
    - references.qmd
    - disclaimer.qmd
  site-url: "https://eurocontrol.int/"
  navbar:
    background: light
    search: false
    title: false
    logo: "images/EUROCONTROL-logo-standard-rgb.svg"
    left:
      - text: "<i class='far fa-star fa-spin fa-fw'></i> Aviation Intelligence"
        #icon: "star"
        menu:
          - text: "**Home**"
            icon: "house-fill"
            href: "https://ansperformance.eu"
            # ---
          - text: "**Balanced Scorecard**"
            icon: "grid-3x3-gap-fill"
            href: "https://www.eurocontrol.int/Economics/BalancedScorecard.html"
            # ---
          - text: "<i class='fas fa-biohazard'></i> **COVID-19 crisis**"
            href: "https://ansperformance.eu/covid/"

          - text: "State and Airline response to Covid-19"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/covid19#response-to-covid-19"

          - text: "Grounded Aircraft"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/covid/acft_ground/"

          - text: "Impact on ANSPs financial situation"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/economics/finance/"

          - text: "Impact on vertical flight efficiency (CCO/CDO)"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/covid/covid_vfe/"
            # ---
          - text: "<i class='fas fa-plane-departure'></i> **Traffic**"
            href: "https://ansperformance.eu/traffic/"

          - text: "<i class='far fa-star fa-spin fa-fw'></i> Daily Traffic Variation & Restart <i class='far fa-star fa-spin fa-fw'></i>"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html"

          - text: "Traffic Forecast"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/traffic/statfor/"
            # ---
          - text: "<i class='fas fa-leaf'></i> **Efficiency & Environment**"
            href: "https://ansperformance.eu/efficiency/"

          - text: "Horizontal Flight Efficiency"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/efficiency/hfe/"

          - text: "Vertical Flight Efficiency"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/efficiency/vfe/"

          - text: "Terminal Holdings"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/efficiency/asma/"

          - text: "Taxi-out"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/efficiency/taxiout/"

           # ---
          - text: "<i class='fas fa-euro-sign'></i> **Economics**"
            href: "https://ansperformance.eu/economics/"

          - text: "Service Units"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"

          - text: "Unit Rates and Costs"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteUnitRates.html"

          - text: "ATM Cost Effectiveness"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/ACE/"

          - text: "ANSPs Financial Situation"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/economics/finance/"

            # ---
          - text: "<i class='fas fa-user-friends'></i> **Stakeholder views**"
            href: "https://ansperformance.eu/dashboard/stakeholder/"

          - text: "Airport View"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/airport/"

          - text: "ANSP View"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/ansp/"

          - text: "FAB View"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/dashboard/stakeholder/fab/"

          - text: "State View"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/dashboard/stakeholder/state/"

            # ---
          - text: "<i class='fas fa-book'></i> **Publications**"
            href: "https://ansperformance.eu/publications/"

            # ---
          - text: "<i class='fas fa-hands-helping'></i> **Reference**"
            href: "https://ansperformance.eu/reference/"

          - text: "Data Download"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/data/"

          - text: "Studies"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/study/"

          - text: "Definitions"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/definition/"

          - text: "Methodology"
            icon: "arrow-return-right"
            href: "https://ansperformance.eu/methodology/"

            # ---
          - text: "<i class='fas fa-external-link-alt'></i> **External**"
            href: "https://ansperformance.eu/"

          - text: "Single European Sky Portal"
            icon: "arrow-return-right"
            href: "https://www.eurocontrol.int/prudata/dashboard/"

          - text: "ICAO GANP"
            icon: "arrow-return-right"
            href: "https://www4.icao.int/ganpportal/"

      - text: "About"
        menu:
          - text: "About the PRC"
            href: "https://ansperformance.eu/about/prc/"

          - text: "About the PRU"
            href: "https://ansperformance.eu/about/us/"

          - text: "Release notes"
            href: "https://ansperformance.eu/post/"

          - text: "Disclaimer"
            href: "https://ansperformance.eu/about/disclaimer/"

      - text: "Areas"
        menu:
          - text: "<i class='fas fa-biohazard'></i> COVID-19 crisis"
            href: "https://ansperformance.eu/covid/"

          - text: "---"

          - text: "Traffic"
            href: "https://ansperformance.eu/traffic/"

          - text: "Capacity & delays"
            href: "https://ansperformance.eu/capacity/"

          - text: "Efficiency & environment"
            href: "https://ansperformance.eu/efficiency/"

          - text: "Economics"
            href: "https://ansperformance.eu/economics/"

      - text: "Views"
        menu:
          - text: "Airports"
            href: "https://ansperformance.eu/dashboard/stakeholder/airport/"

          - text: "Air Navigation Service Provider"
            href: "https://ansperformance.eu/ansp/"

          - text: "Functional Airspace Block"
            href: "https://ansperformance.eu/fab/"

          - text: "State"
            href: "https://ansperformance.eu/dashboard/stakeholder/state/"

      - text: "Publications"
        href: "https://ansperformance.eu/publications/"

      - text: "Reference"
        menu:
          - text: "Data downloads"
            href: "https://ansperformance.eu/data/"

          - text: "Definitions"
            href: "https://ansperformance.eu/definition/"

          - text: "Methodology"
            href: "https://ansperformance.eu/methodology/"

          - text: "Acronyms"
            href: "https://ansperformance.eu/acronym/"

          - text: "Bibliography"
            href: "https://ansperformance.eu/bibliography/"

          - text: "---"

          - text: "<i class='fas fa-xs fa-external-link-alt'></i> ICAO GANP"
            href: "https://www4.icao.int/ganpportal/"

      - text: "SES"
        menu:
          - text: "<i class='fas fa-xs fa-external-link-alt'></i> Single European Sky (SES) Portal"
            href: "https://www.eurocontrol.int/prudata/dashboard/"

