# Treatment of monetary factors in the ace benchmarking analysis

Presentation and comparison of historical series of financial data from different countries poses problems, especially when different currencies are involved, and inflation rates differ. There is a danger that time-series comparisons can be distorted by transient variations in exchange rates.

For this reason, the following approach has been adopted in the analysis for allowing for inflation and exchange rate variation. The financial elements of performance are assessed, for each year, in national currency. They are then converted to national currency in year-N prices using national inflation rates. Finally, for comparison purposes in year-N, all national currencies are converted to Euros using the year-N exchange rate.

This approach has the virtue that an ANSP's performance time series is not distorted by transient changes in exchange rates over the period. It does mean, however, that the performance figures for any ANSP in a given year prior to year-N are not the same as the figures in that year's ACE report, and cannot legitimately be compared with another ANSP's figures for the same year. Cross-sectional comparison using the figures in the ACE analytical report is only appropriate for year-N data.

The exchange rates used to convert the year-N data in Euros are those provided by the ANSPs in their ACE data submission.

The historical inflation figures used in ACE are obtained from EUROSTAT or from the International Monetary Fund when the information is not available in EUROSTAT website. For the projections (future years), the ANSPs' own assumptions concerning inflation rates are used.

Employment costs constitute a major part of ANS provision costs. Staff has to be recruited in local labour markets, and therefore the prevailing wage rates, for many different grades and types of staff, will have a major influence on the overall employment costs. There are a number of ways of measuring differences in prevailing wage levels between different countries. In the ACE benchmarking reports, unit employment costs are also compared when adjusted for Purchasing Power Parities (PPPs). Purchasing Power Parities (PPPs) are currency conversion rates that are applied to convert economic indicators in national currency to an artificial common currency (Purchasing Power Standard (PPS) for EUROSTAT statistics). The PPPs data used to adjust most of the ANSPs employment costs is extracted from EUROSTAT.

For four countries (Armenia, Georgia, Moldova and Ukraine), PPP data is not available in the EUROSTAT database. In these cases, the IMF database is used. Since in the IMF database, the PPPs are expressed in local currency per **international Dollar** rather than **PPS**, an adjustment is made so that the figures used for ARMATS, Sakaeronavigatsia, MOLDATSA and UkSATSE are as consistent as possible with the data used for the rest of the ANSPs. The assumption underlying this adjustment is that the difference in PPPs between two countries shall be the same in the EUROSTAT and in the IMF databases.

There are some limitations[^6] inherent to the use of PPPs and for this reason the ACE data analysis does not put a significant weight on results obtained with PPPs adjustments. PPPs are nevertheless a useful analytical tool in the context of international benchmarking.

[^6]: For instance, it is possible that, for a given country, the cost of living in regions where the ANSP headquarter and other main buildings (e.g. ACCs) are located is higher than the average value computed at national level.
