# TODOs

1. add `cover-image` in yml file
1. ~~insert links and QR code at end of section 1.1~~
1. create a group library on Zotero for biblio entries:
   - ~~sec 1.2~~: ~~Decision No. 88 of the Permanent Commission of EUROCONTROL~~
   - ~~sec 1.2: Specification for Economic Information Disclosure (SEID)~~
   - sec 2.1: SES Regulation on Service Provision
   - ~~sec 2.2~~: ~~SES Service Provision Regulation (EC No 550/2004)~~
   - sec 3.1: ACE 2001-2006 Reports
   - chap 3 footnote 2: ~~Total Factor Productivity of European ANSPs: basic concepts and application” (Sept. 2005)~~
   - ch 4 nd footnote: ~~European airline delay cost reference values, published by the University of Westminster~~
   - what about (Eurostat or IMF): 
      * Purchasing Power Parities (PPPs)
      * Purchasing Power Standard (PPS)
1. Check Westminster URL / Biblio entry
1. show how to use Zotero group to synch bibliographic entries
1. acronyms: link to AIU Portal ones or doc specific/Appendix?
1. select a [citation style](https://quarto.org/docs/authoring/footnotes-and-citations.html#citation-style) 

